### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by vladcrishan** [vladcrishan/MafiaBoss#11]
- [x] Icon values increase/decrease animations (cand creste si scade valoarea la cerc sa fie un efect fain)

- [x] Select answer effect (cand apesi pe o jumatate de imagine - stanga/dreapta - sa apara textul cu efect sub ea)

- [x] Flip card when you touch a second time

### 4 weeks

**Comment by vladcrishan** [comment]
14 August to be done. Maybe add act2 and act3

**Comment by vladcrishan** [comment]
Faci un branch nou care iese din master si pui modificarile din GUI-reform(branch-ul vechi) in primul commit din noul branch. Apoi te pui si faci sa mearga acolo.

**Comment by stefanblaga** [comment]
http://www.coderzheaven.com/2012/09/13/create-blinking-text-android/
https://stackoverflow.com/questions/9294112/how-to-make-the-textview-blinking
https://github.com/hanks-zyh/HTextView
https://github.com/jakob-grabner/Circle-Progress-View

**Comment by stefanblaga** [comment]
- [ ] Scos butoane + mutat imagine mai jos + text view deasupra img pt raspuns

- [ ] Click jumate de img => incarcat raspuns in text view

- [ ] Dublu click pe jumate de img mers mai departe (answer)

- [ ] dublu click pe juma de imagine si flip image in sensul click-ului (stanga sau dreapta)

**Comment by stefanblaga** [comment]
Link-uri catre flip card animation
https://developer.android.com/training/animation/cardflip.html
https://www.thedroidsonroids.com/blog/android/android-flipa-card-animation-exlpained/
