### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by vladcrishan** [vladcrishan/MafiaBoss#12]
- [x] App Icon
- [x] Colors
- [x] Menu design
- [x] Icons, sizes

### 3 weeks

**Comment by stefanblaga** [comment]
1. Muta cod progres bar animation in testActivity
2. Modifica animatia la progressBar sa fie mai fluida
3. Modifica schimbarea culorilor la progressBar sa fie mai fluide

p.s. nu lasa cod nefolositor!
